quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;
    username: sa
    password: sa

  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    log:
      format-sql: false
      active: false

  mailer:
    mock: true
    from: noreply@codelevel.com

  rest-client:
    identity-api:
      url: http://localhost:8081/api
    course-api:
      url: http://localhost:8081/api
    student-progress-api:
      url: http://localhost:8081/api
    linkedin-api:
      url: http://localhost:8081
    instagram-api:
      url: http://localhost:8081

integration:
  mock-publishing: true