greeting:
  message: "hello"

quarkus:
  http:
    cors:
      enabled: true
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "Content-Type,Authorization,Content-Disposition"
      exposed-headers: "Authorization"
    root-path: /api
    port: 8080

  flyway:
    active: true

  cache:
    caffeine:
      user-cache:
        expire-after-write: 30M
        expire-after-access: 10M
        initial-capacity: 200
        maximum-size: 5000
      user-list-cache:
        expire-after-write: 2M
        expire-after-access: 1M
        initial-capacity: 1
        maximum-size: 10

integration:
  linkedin:
    access-token: ${LINKEDIN_ACCESS_TOKEN:}
    author-urn: ${LINKEDIN_AUTHOR_URN:}
  instagram:
    access-token: ${INSTAGRAM_ACCESS_TOKEN:}
    user-id: ${INSTAGRAM_USER_ID:}

mp:
  jwt:
    verify:
      publickey:
        location: ${JWT_PUBLIC_KEY_LOCATION:classpath:/META-INF/resources/publicKey.pem}
      issuer: https://app.codelevel.club

smallrye:
  jwt:
    sign:
      key:
        location: ${JWT_PRIVATE_KEY_LOCATION:classpath:/META-INF/resources/privateKey.pem}
