-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into myentity (id, field) values(1, 'field-1');
-- insert into myentity (id, field) values(2, 'field-2');
-- insert into myentity (id, field) values(3, 'field-3');
-- alter sequence myentity_seq restart with 4;

-- Criar Roles
-- INSERT INTO cl_role (id, r_name, r_description) VALUES (nextval('cl_role_seq'), 'ROLE_USER', 'Usuário comum do sistema');
-- INSERT INTO cl_role (id, r_name, r_description) VALUES (nextval('cl_role_seq'), 'ROLE_ADMIN', 'Administrador do sistema');
-- INSERT INTO cl_role (id, r_name, r_description) VALUES (nextval('cl_role_seq'), 'ROLE_MANAGER', 'Gerente com permissões intermediárias');
--
-- -- Criar Permissions
-- INSERT INTO cl_permission (id, p_name, p_description) VALUES (nextval('cl_permission_seq'), 'users.read', 'Visualizar usuários');
-- INSERT INTO cl_permission (id, p_name, p_description) VALUES (nextval('cl_permission_seq'), 'users.write', 'Criar e editar usuários');
-- INSERT INTO cl_permission (id, p_name, p_description) VALUES (nextval('cl_permission_seq'), 'users.delete', 'Deletar usuários');
--
-- -- Associar Permissions às Roles
-- -- ROLE_USER (apenas leitura de relatórios)
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (1, 4);
--
-- -- ROLE_MANAGER (leitura de usuários e relatórios completos)
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (3, 1);
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (3, 4);
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (3, 5);
--
-- -- ROLE_ADMIN (todas as permissões)
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (2, 1);
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (2, 2);
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (2, 3);
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (2, 4);
-- INSERT INTO cl_role_permission (role_id, permission_id) VALUES (2, 5);

-- Criar usuário admin de teste (senha: admin123)
-- INSERT INTO cl_user (id, u_username, u_pass, u_email, u_public_id, u_enabled)
-- VALUES (nextval('cl_user_seq'), 'admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'admin@codelevel.com', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', true);

-- Associar admin à ROLE_ADMIN
-- INSERT INTO cl_user_role (user_id, role_id) VALUES (1, 2);