-- Migrate all userId/instructorId/creatorId FK columns from BIGINT to UUID
-- to align with the publicId field exposed via JWT sub claim.

-- community module
ALTER TABLE CL_QUESTION ALTER COLUMN q_user_id UUID NOT NULL;
ALTER TABLE CL_ANSWER ALTER COLUMN a_user_id UUID NOT NULL;
ALTER TABLE CL_VOTE ALTER COLUMN v_user_id UUID NOT NULL;

-- course module
ALTER TABLE CL_COURSE ALTER COLUMN co_instructor_id UUID;

-- course_requests module
ALTER TABLE CL_COURSE_REQUEST ALTER COLUMN creq_requester_id UUID NOT NULL;
ALTER TABLE CL_COURSE_REQUEST ALTER COLUMN creq_assigned_instructor_id UUID;
ALTER TABLE CL_COURSE_REQUEST_VOTE ALTER COLUMN creqv_user_id UUID NOT NULL;

-- student_progress module
ALTER TABLE CL_COURSE_ENROLLMENT ALTER COLUMN ce_user_id UUID NOT NULL;
ALTER TABLE CL_LESSON_PROGRESS ALTER COLUMN lp_user_id UUID NOT NULL;
ALTER TABLE CL_EXERCISE_ATTEMPT ALTER COLUMN ea_user_id UUID NOT NULL;
ALTER TABLE CL_LEARNING_PATH ALTER COLUMN lpath_creator_id UUID NOT NULL;

-- reviews_feedbacks module
ALTER TABLE CL_COURSE_REVIEW ALTER COLUMN cr_user_id UUID NOT NULL;
ALTER TABLE CL_LESSON_FEEDBACK ALTER COLUMN lf_user_id UUID NOT NULL;

-- gamification module
ALTER TABLE CL_XP_TRANSACTION ALTER COLUMN xpt_user_id UUID NOT NULL;
ALTER TABLE CL_USER_STREAK ALTER COLUMN us_user_id UUID NOT NULL;
ALTER TABLE CL_USER_ACHIEVEMENT ALTER COLUMN ua_user_id UUID NOT NULL;

-- certificate module
ALTER TABLE CL_CERTIFICATE ALTER COLUMN cert_user_id UUID NOT NULL;

-- integration module
ALTER TABLE CL_SOCIAL_MEDIA_POST ALTER COLUMN smp_user_id UUID NOT NULL;
